language: python

python:
  - "2.7"

before_script:
  - pip install flake8 pycodestyle pep8-naming
  - flake8 --version
  - flake8 -v .
  - python setup.py sdist install

script:
  - python setup.py test -vvv